feat: add recent challenges UI
hxckr-org/hxckr-web pull request #37
Opened 2024-11-18 23:03 UTC by Extheoisah

2024-11-19 14:31 UTC, Extheoisah commented
Screens:
<img width="2056" alt="Screenshot 2024-11-19 at 15 27 47" src="https://github.com/user-attachments/assets/b64e18da-3d5e-4a28-abc7-293973256ac4">
<img width="2056" alt="Screenshot 2024-11-19 at 15 28 02" src="https://github.com/user-attachments/assets/c4ab6c95-4650-42a1-b727-41c6ee930c0c">

2024-11-19 16:46 UTC, daviroo requested changes

2024-11-19 17:20 UTC, Extheoisah commented on src/app/components/sections/recent-challenges.tsx
> +        status: "not_started",
This is dummy data I was using. Its no longer needed so I'll remove it

2024-11-20 08:29 UTC, daviroo approved these changes

2024-11-20 09:10 UTC, merged